apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #  - github.com/opendatahub-io/kserve/config/default?ref=v0.10.2
  - github.com/israel-hdez/kserve/config/default?ref=manifests-openshift-adaption-010

